---
# IP address for OpenConrail (e.g. 192.168.0.2)
contrail_ip:

# Gateway address for OpenConrail (e.g. 192.168.0.1)
contrail_gateway:

# Interface name for OpenConrail (e.g. eth0)
contrail_interface:


# IP address for OpenStack VM (e.g. 192.168.0.3)
openstack_ip:

# OpenStack branch used on VMs.
openstack_branch: master

# If true, then install networking_bgpvpn plugin with contrail driver
install_networking_bgpvpn_plugin: false

# If true, password to the created instances will be set to 'uberpass1'
change_password: false

# Set to true if you have conflict between docker network subnet and your local network subnet
fix_docker_bip: false

# Set to true to print out project synchronization status
print_synchronized_projects: true