---
# IP address for OpenConrail (e.g. 192.168.0.2)
contrail_ip:

# Gateway address for OpenConrail (e.g. 192.168.0.1)
contrail_gateway:

# Interface name for OpenConrail (e.g. eth0)
contrail_interface:


# IP address for Openstack VM (e.g. 192.168.0.3)
openstack_ip:

# Openstack branch used on VMs.
openstack_branch: stable/ocata
