---
- name: Install system requirements
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip

- name: Update local.conf with enabling plugin
  lineinfile:
    path: ~/devstack/local.conf
    regexp: '^enable_plugin networking-bgpvpn'
    line: 'enable_plugin networking-bgpvpn https://git.openstack.org/openstack/networking-bgpvpn.git stable/ocata'
    insertafter: 'enable_plugin'

- name: Update local.conf with driver
  lineinfile:
    path: ~/devstack/local.conf
    regexp: '^NETWORKING_BGPVPN_DRIVER'
    line: 'NETWORKING_BGPVPN_DRIVER="BGPVPN:OpenContrail:neutron_plugin_contrail.plugins.opencontrail.networking_bgpvpn.contrail.ContrailBGPVPNDriver:default"'
    insertafter: 'enable_plugin'

- name: Prepare directory for fetching repository
  become: true
  file:
    path: /opt/stack/networking-bgpvpn
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0775

- name: Fetch git repository
  git:
    repo: "https://git.openstack.org/openstack/networking-bgpvpn.git"
    dest: /opt/stack/networking-bgpvpn
    version: "{{ openstack_branch }}"
    accept_hostkey: yes
    force: yes

- name: Move source of neutron to post-config phase
  lineinfile:
    state: absent
    path: /opt/stack/networking-bgpvpn/devstack/plugin.sh
    regexp: '^source \$NEUTRON_DIR/devstack/lib/l2_agent$'

- name: Move source of neutron to post-config phase
  lineinfile:
    state: present
    path: /opt/stack/networking-bgpvpn/devstack/plugin.sh
    line: '        source $NEUTRON_DIR/devstack/lib/l2_agent'
    insertbefore: 'plugin_agent_add_l2_agent_extension'

- name: fix requirements.txt
  lineinfile:
    path: /opt/stack/networking-bgpvpn/test-requirements.txt
    state: absent
    regexp: 'networking-odl'

- name: copy pip dependencies
  copy:
    src: "../files/{{ item }}"
    dest: /tmp
  with_items:
    - 'cfgm_common-0.1.dev0.tar.gz'
    - 'vnc_api-5.0.0.tar.gz'

- name: install dependencies
  pip:
    name: "{{ item }}"
  become: yes
  with_items:
    - '/tmp/cfgm_common-0.1.dev0.tar.gz'
    - '/tmp/vnc_api-5.0.0.tar.gz'
    - 'git+git://github.com/Juniper/contrail-neutron-plugin.git#egg=neutron_plugin_contrail'
